### ISSUE TITLE
Improve the Service Principal AuthN Flow to Use the Azure Login Action

### ISSUE THREAD

**Issue by markti** [markti/terraform-github-azure-terraformer#9]
DESIGN OVERVIEW

instead of THREE environment variables and ONE secret we need ONE secret with a JSON blob in it:

```
{
    "clientId": "<GUID>",
    "clientSecret": "<secret>",
    "subscriptionId": "<GUID>",
    "tenantId": "<GUID>",
    (...)
}
```

Then we need to use this action

```
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
```

STEP 1

We currently use a module to encapsulate the SP credentials here:

modules/credential/azure/service-principal

However, with this approach we only need one

resource "github_actions_environment_secret" "client_secret" {
  repository      = var.repository
  environment     = var.environment
  secret_name     = "AZURE_CREDENTIALS"
  plaintext_value = JSONENCODE(...)
}

STEP 2

Update the core workflow YAMLS files here:

modules/pipeline/terraform/manual-targeting/files/.github/workflows/terraform-plan.yaml
modules/pipeline/terraform/manual-targeting/files/.github/workflows/terraform-apply.yaml
modules/pipeline/terraform/manual-targeting/files/.github/workflows/terraform-destroy.yaml

With the "azure/login@v1" task before we execute the corresponding Terraform command. We should be able to shed the ARM_ prefixed environment variables from the Terraform command's step since we will already be logged in (requires testing).
